README.md
=> Improve README, append link to create account on MangoPay website

README.md
Fix some ClientId typo in README
=> Fix ClientId to ClientID in README refs #20

.travis.yml, README.md, mangopaysdk/tools/storages/defaultstoragestrategy.py, setup.py
Hi,
I replaced the deprecated package lockfile by fasteners.
Guillaume
=> Replace deprecated lockfile by fasteners

mangopaysdk/types/payinpaymentdetailsdirectcard.py
PayInPaymentDetailsDirectCard's parent class should be PayInPaymentDetails instead of PayInExecutionDetails
=> Fixes PayInPaymentDetailsDirectCard parent class; resolves #51

requirements.txt, tests/testbase.py
Please note that in the diff there are a lot more changes due to either mixed newline characters or extraneous white spaces in the original file
=> Tests, setup certifi package to avoid SSL warnings

mangopaysdk/types/payinexecutiondetailsdirect.py
Hi,
Please check my comment: https://github.com/Mangopay/mangopay2-python-sdk/issues/62
=> Add SecureModeNeeded property to PayInExecutionDetailsDirect

mangopaysdk/entities/payin.py, mangopaysdk/tools/apibase.py, mangopaysdk/types/payinpaymentdetailspaypal.py, tests/testpayins.py
Note that this functionality is currently only available in private beta.
=> Implemented payins by PayPal

mangopay/resources.py
=> Implement `PayIn.cast()`

mangopay/base.py, mangopay/query.py, mangopay/utils.py, tests/test_payins.py, tests/test_utils.py
=> Improve compatibility with v2

mangopay/api.py
Fix for #96 based on suggestion
=> Fix for #96

.gitignore, docs/usage.rst, mangopay/resources.py, tests/test_banking_aliases.py
=> Banking aliases support

mangopay/api.py
=> Enhance logging

mangopay/fields.py
=> Remove double encoding

mangopay/api.py, mangopay/resources.py, tests/test_base.py, tests/test_cards.py
Altered APIRequest object to allow launching custom requests, needed for authorizing a Card Registration in order to retrieve a Card entity.
=> Implemented Get PreAuthorizations for a Card endpoint.

mangopay/resources.py, tests/test_bankaccounts.py
Apologies for the commit message.
=> Implemented Get Transactions for a Bank Account.

mangopay/resources.py, tests/test_mandates.py
Sorry about the commit message
=> Implemented Get Transactions for a Mandate.

mangopay/api.py, mangopay/constants.py, mangopay/fields.py, mangopay/resources.py, mangopay/utils.py, tests/test_clients.py, tests/test_payins.py, tests/test_preauthorizations.py
Re-enabled tests which were disable due to this missing feature
=> Implemented AVS support

mangopay/resources.py
Add missing field ComanpyNumber for LegalUser
=> Add CompanyNumber for LegalUser

setup.py
=> Add pytz as a required in setup.py

mangopay/resources.py, tests/test_clients.py
Added headquarter's phone number to Client entity.
Upgraded client upload test to check phone number field.
=> MPSDK-270 Headquarters phone number

requirements/base.txt, requirements/development.txt
For security reasons, pyopenssl has to be updated.
=> Update pyopenssl version

mangopay/query.py, mangopay/resources.py, tests/test_emoney.py
=> GET users/emoney/ multi-period support

mangopay/api.py, mangopay/constants.py, mangopay/fields.py, mangopay/resources.py, mangopay/utils.py, tests/test_payins.py
=> ApplePay Payins support

docs/usage.rst
https://github.com/Mangopay/mangopay2-python-sdk/issues/219
=> https://github.com/Mangopay/mangopay2-python-sdk/issues/219

mangopay/base.py
=> small handler change in save function

mangopay/fields.py
[Fixes this issue](https://github.com/Mangopay/mangopay2-python-sdk/issues/290)
=> MPSDK-929: Fixed datetime bug

mangopay/resources.py
[fixes this issue](https://github.com/Mangopay/mangopay2-python-sdk/issues/299)
=> MPSDK-971: fixed this issue

mangopay/resources.py, tests/test_conversion.py
added quote endpoints
rename InstantConversion to Conversions
=> Conversions Quote

mangopay/resources.py
Closes https://github.com/Mangopay/mangopay2-python-sdk/issues/369
=> Add DirectPayIn.preferred_card_network to match documentation

mangopay/constants.py
Adds VIRTUAL_ACCOUNT_ACTIVE, VIRTUAL_ACCOUNT_BLOCKED, VIRTUAL_ACCOUNT_CLOSED, VIRTUAL_ACCOUNT_FAILED in EVENT_TYPE_CHOICES
=> Add EventTypes [Choices] for Virtual Accounts

mangopay/resources.py
Adds missing fields: DebitedFunds, Feeds (MoneyField)
=> Add missing BankWirePayInExternalInstruction fields

mangopay/api.py, mangopay/ratelimit.py, tests/test_rate_limit.py
=> [improvement] updated the way rate limits are set

mangopay/resources.py, tests/test_payins.py
- added support for API endpoints
=> [feature] recurring paypal payins

mangopay/resources.py
=> [bugfix] added missing fields

mangopay/resources.py
=> [bugfix] non snake-case fields
